# Generated by Django 3.0.5 on 2020-04-10 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memo_card', '0004_memocard_pl_bold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_on', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_users', to='memo_card.MemoCard')),
                ('user_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_memocard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
