# Generated by Django 3.0.5 on 2020-04-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_card', '0006_repeat_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeat',
            name='repeat_on',
            field=models.DateField(),
        ),
    ]
