# Generated by Django 3.0.5 on 2020-04-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_card', '0010_categorymemocard_usermemocard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymemocard',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categorymemocard',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermemocard',
            name='eg',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usermemocard',
            name='reverse_eg',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usermemocard',
            name='reverse_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usermemocard',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
