# Generated by Django 3.0.5 on 2020-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_last_card_generaterd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_card_generaterd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='new_card_number',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
